INSERT INTO owners DEFAULT VALUES;
INSERT INTO owners DEFAULT VALUES;
INSERT INTO owners DEFAULT VALUES;
INSERT INTO owners DEFAULT VALUES;
INSERT INTO owners DEFAULT VALUES;
INSERT INTO owners DEFAULT VALUES;
INSERT INTO owners DEFAULT VALUES;
